---
# tasks file for fresh-install-setup
- name: Install packages and configure fresh archlinux based install
  hosts: localhost
  gather_facts: true
  become: true
  collections:
    - community.general.pacman
  vars:
    username: fatman9000
    dotfiles:
      url: https://github.com/Fatman9000/dotfiles.git
      destination: projects/dotfiles
      rcup_flags: -fx README.md
    repos:
      - extra
      - multilib

  tasks:
    - name: Update package repositories
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Enable pacman colourised output and verbose package lists
      replace:
        path: /etc/pacman.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: "^#Color$", replace: "Color" }
        - { regexp: "^#VerbosePkgLists$", replace: "VerbosePkgLists" }

    - name: Enable repositories
      replace:
        path: /etc/pacman.conf
        regexp: '^#\[{{ item }}\]$\n^#Include\s+=\s+/etc/pacman.d/mirrorlist$'
        replace: '[{{ item }}]\nInclude = /etc/pacman.d/mirrorlist'
      with_items: "{{ repos }}"
      notify: Update pacman cache
      when: repos is defined

    - name: Install basic utils, shells, apps
      community.general.pacman:
        name:
          - xorg
          - kitty
          - vlc
          - gimp
          - git
          - vim
          - source-highlight
          - tree
          - base-devel
          - stow
        state: present

    - name: Install archival utils
      community.general.pacman:
        name:
          - atool
          - p7zip
          - unrar
          - unzip
          - xz
          - zip
          - bzip2
          - gzip
          - tar
        state: present

    - name: Install required packages
      community.general.pacman:
        name:
          - firefox
          - kitty
          - lutris
          - discord
          - steam
          - keepassxc
          - helix
          - code
          - wine-staging
          - libreoffice-fresh
          - yakuake
        state: present

    - name: Install download utils
      pacman:
        name:
          - aria2
          - curl
          - wget
        state: present

    - name: install zsh
      community.general.pacman:
        name:
          - zsh
          - zsh-completions
          - zsh-syntax-highlighting
          - fzf
        state: present

    - name: install KDE and KDE apps
      community.general.pacman:
        name:
          - plasma-meta
          - kde-applications-meta
          - sddm-kcm
        state: present

    - name: Change "{{ username }}"'s shell to zsh
      become: true
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh

    - name: Install oh-my-zsh for users
      become: true
      become_user: "{{ username }}"
      ansible.builtin.shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      args:
        chdir: "~{{ username }}"

    - name: Fetch and stow dotfiles
      ansible.builtin.git:
        repo: https://github.com/Fatman9000/dotfiles.git
        dest: "~/{{ username }}"
      args:
        chdir: "~/{{ username }}/dotfiles"