---
- name: Install packages and configure fresh archlinux based install
  hosts: localhost
  become: true
  vars:
    arch_gpu_drivers:
      NVIDIA: "nvidia"
      AMD: "mesa"

  tasks:
    - name: Update package repositories
      community.general.pacman:
        update_cache: true

    - name: Check GPU Manufacturer
      command: "lspci | grep -i VGA"
      register: gpu_info
      changed_when: false
      ignore_errors: true

    - name: Install GPU Drivers
      community.general.pacman:
        name: "{{ arch_gpu_drivers[gpu_info.stdout_lines[0] | regex_search('NVIDIA|AMD')] }}"
        state: present
      when: gpu_info.stdout_lines[0] | regex_search('NVIDIA|AMD')
      ignore_errors: true

    - name: Install required packages
      community.general.pacman:
        name:
          - firefox
          - kitty
          - lutris
          - discord
          - steam
          - keepassxc
          - neovim
          - code
          - wine-staging
          - libreoffice-fresh
        state: present
