---
- name: Install packages and configure fresh archlinux based install
  hosts: localhost
  become: yes
  vars:
    arch_gpu_drivers:
      NVIDIA: "nvidia"
      AMD: "mesa"  # For AMD GPUs, the open-source mesa drivers are usually sufficient.

  tasks:
    - name: Update package repositories
      pacman:
        update_cache: yes

    - name: Check GPU Manufacturer
      command: "lspci | grep -i VGA"
      register: gpu_info
      changed_when: false
      ignore_errors: yes

    - name: Install GPU Drivers
      pacman:
        name: "{{ arch_gpu_drivers[gpu_info.stdout_lines[0] | regex_search('NVIDIA|AMD')] }}"
        state: present
      when: gpu_info.stdout_lines[0] | regex_search('NVIDIA|AMD')

    - name: Install required packages
      pacman:
        name:
          - discord
          - steam
          - plasma
          -
        state: present
